### ISSUE TITLE
TCI support

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#114]
We need to finish implementation of TCI so it's at least controllable via GUI.

Todos:
- [x] Add TCI field next to Hamlib 
- [x] Add Startup via Daemon
- [ ] Change Hamlib related functions to "radio" related function and variable names 

<hr>

https://github.com/maksimus1210/TCI/blob/master/doc/TCI_interface_1.6.pdf

I hope that the TCI protocol is implemented relatively soon in the project:

TCI – Transceiver Control Interface is the network interface for control, data transfer and synchronization between a transceiver/receiver, logger, digital software, skimmer, other software and external power amplifier, band filters, antenna switch, radio station controller and other devices.

https://github.com/maksimus1210/TCI

Software like MSHV, JTDX etc is using this. It's not limited to SunSDR tranceivers. 

Using TCI you don't need any external/thirdparty VAC as this goes trough websocket

73 de LA3QMA
Kai Gunter

**Comment by DJ2LS** [comment]
https://github.com/Hamlib/Hamlib/issues/736

**Comment by LA3QMA** [comment]
> [Hamlib/Hamlib#736](https://github.com/Hamlib/Hamlib/issues/736)

They have changed the link for the protocol to: https://github.com/ExpertSDR3/TCI
I can ask if they can remove/update the old as this is not up to date regarding audio in/out

**Comment by DJ2LS** [comment]
closing this as completed. Further adjustments can be done later.
