### ISSUE TITLE
Session disconnect too short --> causes heartbeat toggle

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#173]
Session disconnect too short --> causes heartbeat toggle.
We need to track down this problem as its causes a really bad tnc state.

**Comment by DJ2LS** [comment]
We also need to avoid the toggle somehow in case of a disconnect frame loss

**Comment by kronenpj** [comment]
Unfortunately this fix causes the receiving TNC to remain in BUSY / OPEN after experiencing the same RF / audio state which caused issue #179. In this state, the TNC does not properly respond to GUI commands until the session times out in ~12 minutes.  

I may start writing tests for the TNC state machine transitions. I need to understand the `ctest` approach first.

**Comment by DJ2LS** [comment]
Thanks, @kronenpj for having a look!

On which side does the TNC not respond to commands? ISS or IRS ?

Regarding to the ctests, please also have a look at https://github.com/DJ2LS/FreeDATA/issues/102

**Comment by kronenpj** [comment]
IRS. I implemented the TODO from this commit and it fixes this case as well.

**Comment by DJ2LS** [comment]
mh, there seems to be another problem with connecting - actually we can't establish a ARQ connection anymore... 🤔

**Comment by kronenpj** [comment]
This appears to be fixed with PR #183.
