### ISSUE TITLE
sounddevice present multiple times in the dropdown list

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#174]
The speaker/microphone sounddevice is always present multiple times in the respective dropdown list.
It doesn't seem to make a difference which one you choose, but it is irritating.

Problem occured on Windows 10 and Windows 11:

![image](https://user-images.githubusercontent.com/58949681/163992113-2d1d2673-5ca7-4055-9ff9-c2fb3b32d550.png)

**Comment by kronenpj** [comment]
@dk5sm - Are you able / willing to build from source? If so, please clone the repository, check out `issue_174_fix` branch and build it. Let us know if that solves the issue for you.

**Comment by kronenpj** [comment]
@dk5sm I figured out how to create builds manually. I've created a release on my fork:
https://github.com/kronenpj/FreeDATA-experiments/releases/tag/v0.4.3-alpha

**Comment by dk5sm** [comment]
Paul,
I installed your fork-release on my Windows 10 machine, but it seems not to fix the issue. Instead, I have no more audio device:
![image](https://user-images.githubusercontent.com/58949681/175803572-e962dd2a-273f-4064-8a95-044a0d0c8e88.png)

**Comment by kronenpj** [comment]
Stefan,

Hmm. I'll try again :).

**Comment by kronenpj** [comment]
@dk5sm - I've re-built and re-uploaded the packages to the release (same URL). This time I tested that sound cards are listed. I can't go further as I don't run Windows on a machine connected to a radio.

**Comment by dk5sm** [comment]
This build shows audio devices again, but it seems that all devices ever connected and also currently not present devices are in the list:
![image](https://user-images.githubusercontent.com/58949681/175925907-19d026d4-ed3d-403b-b9b0-ebf714de5b4c.png)

This is what is shown in widows control panel & device manager:
![image](https://user-images.githubusercontent.com/58949681/175926027-83c6a992-4142-4bfe-a2a6-cacc11ef8543.png)

**Comment by kronenpj** [comment]
@dk5sm I've added another (replaced) the packages in my repository. There will be an "error" level message listing the devices along with all the attributes the `sounddevice` module collects. I'll try to use that to filter out non-installed devices - if enough information is provided.

**Comment by kronenpj** [comment]
@dk5sm I've updated the build and have new packages for you to try. They're available for download here:
https://github.com/DJ2LS/FreeDATA/actions/runs/3071502608

Please try them and let me know if the problem is resolved.
@DJ2LS

**Comment by DJ2LS** [comment]
Next release adds device checksums so they can be identified. 
A first test run shows, that we have unique checksums, therefore we have different devices. Next step will be, determining the differences between equal name

**Comment by DJ2LS** [comment]
Solved, because it's a feature, not a bug. Added Host-API Names to Device Name
