### ISSUE TITLE
app version in the title bar not shown

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#175]
minor glitch: sometimes the version display in the title bar is not shown on startup:

![image](https://user-images.githubusercontent.com/58949681/164007894-05727256-21e4-4471-8774-a533f6544e0d.png)

Bug noticed on Windows 10/11.

**Comment by DJ2LS** [comment]
@dk5sm has this bug been fixed with the latest release?

**Comment by dk5sm** [comment]
Simon, it seems so. Has not occurred again with me. Von: DJ2LSGesendet: Montag, 2. Mai 2022 06:51An: DJ2LS/FreeDATACc: Stefan DK5SM; MentionBetreff: Re: [DJ2LS/FreeDATA] app version in the title bar not shown (Issue ***@***.*** has this bug been fixed with the latest release?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
