### ISSUE TITLE
ADIF compatible logfile & UDP port

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#178]
I would like to propose an ADIF compatible logging. In the first step an output to a file might be sufficient; maybe later on a sending via "ADIF UDP" to a supported logging application is feasible as an alternative.

**Comment by DJ2LS** [comment]
@dk5sm do we need an adif log for every single message or would it be enough, just opening message info screen and sending a adif entry manually via UDP?

**Comment by DJ2LS** [comment]
https://www.npmjs.com/package/tcadif

https://www.npmjs.com/package/adif-parser-ts

**Comment by dk5sm** [comment]
UDP is a good thing, but requires the logging application to be listening at that time. Guess, that for this reason sometimes qso´s will not be logged and will get lost. I´d prefer a solution with an additional cumulative logging file (not one file per qso/contact).

**Comment by SpudGunMan** [comment]
suggestions for logging function on the first successful link to a new callsign or have a button on the "submenu" for logging ad-hoc

**Comment by DJ2LS** [comment]
What if we add a "adif" button next to a message and let the user decide which message to send via UDP to a logging server? 

Another approach might be, adding a adif button which opens then a user dialog. The user then can fill the necessary data and pushing it via UDP as well.

**Comment by DJ2LS** [comment]
I think this one becomes more and more or interest. Thinking about it a bit. And brings me to the point, implementing some simple UDP logging instead of using static adif files. 

Placing a "log" button next to each message, sending directly via UDP

**Comment by DJ2LS** [comment]
@dk5sm  Time for closing this one soon. It's the oldest issue here.

I will implement it like this:

- Adif button next to each message 
- Logging only via UDP ADIF
- only pet message logging - no adif files

**Comment by DJ2LS** [comment]
Ready for testing

**Comment by DJ2LS** [comment]
Webshould add Common Ports to the gui so it's easier selecting them. Port vs Application

**Comment by dk5sm** [comment]
As the UDP Port for logging ist flexible and not predefined in some logging applications, i'd suggest keeping this as it is right now (unfilled). This forces the user to check with the correct port instead of using a (false) predefined entry which will probably not work.

How to article in the Wiki may be an alternative way to support the user.

**Comment by DJ2LS** [comment]
That's a part then for @LA3QMA 🙂
