### ISSUE TITLE
chat cannot be deleted

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#190]
Clicking on "Delete chat" leads to a chat window reload, but has no further effect:

![image](https://user-images.githubusercontent.com/58949681/168489324-e5b43dd4-da30-449a-9c44-36fb82267f0a.png)

**Comment by DJ2LS** [comment]
We also should add an option deleting single messages as additional feature.

**Comment by DJ2LS** [comment]
@dk5sm Could you press `Ctrl+Shift+i `for opening the GUIs debugging console while the chat is openend? Then Try deleting the chat again and write the debugging output here. Thanks!

**Comment by DJ2LS** [comment]
Further inspection has been showing, we need to catch errors in `preload-chat.js:515`

**Comment by DJ2LS** [comment]
> @dk5sm Could you press `Ctrl+Shift+i `for opening the GUIs debugging console while the chat is openend? Then Try deleting the chat again and write the debugging output here. Thanks!

@dk5sm , could you check this again with the new error message which should be now displayed ?

**Comment by DJ2LS** [comment]
Lines of interest:

```
app.asar\preload-chat.js:516 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at update_chat (VM425 C:

```

**Comment by DJ2LS** [comment]
```
Object
VM115 preload-chat.js:515 error with database parsing...
VM115 preload-chat.js:516 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at update_chat (VM115 preload-chat.js:470:28)
    at VM115 preload-chat.js:77:13
    at Array.forEach (<anonymous>)
    at VM115 preload-chat.js:75:21
    at processTicksAndRejections (VM320 task_queues:96:5)
```
