### ISSUE TITLE
Chat: weird transmission state and IRS did not receive anything

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#192]
The following screenshot shows a weird transmission state - transfer of first message is not completed and and the second one is supposedly already started:
![image](https://user-images.githubusercontent.com/58949681/168489623-08269480-dae7-491f-afec-6bab3980a158.png)

After timeout, this state is shown, but IRS did not receive *any* of both messages:
![image](https://user-images.githubusercontent.com/58949681/168489679-4e39cde6-bf41-4951-aeed-6c7c2915e6f0.png)

The problem occurred with strongly changing conditions around 0dB SNR.

**Comment by DJ2LS** [comment]
@dk5sm the latest release (alpha.9) contains a bug fix which could have solved the problem with arq transmission. 
However, we need to optimize GUI as well.
