### ISSUE TITLE
session disconnect ignored

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#197]
session disconnect will be ignored.
Maybe we need to add this to callsign whitelist

**Comment by DJ2LS** [comment]
Not sure if really a big. Occurred once. We might keep this in mind

**Comment by DJ2LS** [comment]
When closing the TNC on IRS and starting it again while an ongoing transmission, and then sending a stop/disconnect on ISS, the frame is unknown.

**Comment by kronenpj** [comment]
If the STOP frame (type #249) is received via the frame allow list then we would need to do additional processing to decide whether to act upon that frame. Otherwise any / every STOP frame received will cause a disconnection of a session. We don't want that. :)

**Comment by kronenpj** [comment]
Looking at this a little deeper. If the STOP frame has the checksum for `mycallsign` the frame should be processed. Let me create a test case to see how the TNC behaves in a similar scenario.

**Comment by DJ2LS** [comment]
I also had the case, that we got a signalling frame toggle 🤔 but this doesn't occur often. However, we need a fox for this as soon as it's clear what exactly happens

**Comment by kronenpj** [comment]
The TNC will process any `STOP` frame addressed to that station regardless of ARQ connection status. The positive test verifies this and the negative verifies that the station ignores stop frames not addressed to it. Code is in PR #227.
