### ISSUE TITLE
[Feature] drag n drop for chat 

### ISSUE THREAD

**Issue by computer-wizard** [DJ2LS/FreeDATA#199]
It should be very nice if you can transfer binary files like pictures, etc. using RF-chat.
I mean that a copied binary file is transmitted when it is pasted/dropped  in the RF-chat window. 
In the remote RF-chat window an icon will appear with the name of the file or picture what can be
opened to see the contents when the download is completed.

**Comment by computer-wizard** [comment]
Or in chase of a picture, directly the picture is displayed in the receiving remote RF chat window.

**Comment by DJ2LS** [comment]
Hi, @computer-wizard sending pictures and other files via RF Chat is already possible. Just select a file by clicking the staple right of the text field. Then you can send a message + a file. Or are you talking about "drag and drop" ? 

The other feature with image and file preview is planned, but we are focusing on core stability first.

**Comment by computer-wizard** [comment]
Yes, I was also talking about drag and drop.

**Comment by DJ2LS** [comment]
Okay, I'd like to rename this issue to "drag and drop like behavior for chat" so its more clear. 
This needs a big rewrite of the actual data transmission part within chat, so might need some time until this is implemented. But I like to see this feature as well :smile:

**Comment by DJ2LS** [comment]
> Or in chase of a picture, directly the picture is displayed in the receiving remote RF chat window.

@computer-wizard this should be possible in a really basic way with the next release. However, images should be really small because of low speed. Theres also not yet a nice modal for displaying the images. This can be done in future releases.

**Comment by DJ2LS** [comment]
The new gui supports drag n drop, when dragging a file to the input field for selecting files.

**Comment by DJ2LS** [comment]
@Mashintime can you have a look regarding to this? It's time for closing this if it's working or adjusting it 🙂

**Comment by DJ2LS** [comment]
implemented, working for "new message area"

![grafik](https://github.com/user-attachments/assets/bc4c0f19-a515-422a-b2e1-26a72fbece74)


there is no additional information for keeping things simple.
