### ISSUE TITLE
Possible logic error in data_handler while deciding between low- and high-bandwidth mode frame types

### ISSUE THREAD

**Issue by kronenpj** [DJ2LS/FreeDATA#218]
**Describe the bug**
In `arq_open_data_channel` the decision point to choose between frame type 227 vs 225 (narrow or wide) is slightly flawed. The decision checks  `static.LOW_BANDWIDTH_MODE and mode==255`. Since `mode` 255 is an unused option, the TNC always chooses to open the ARQ channel with frame type 225 (wide) which may be inconsistent with the operator's choice of `LOW_BANDWIDTH_MODE`.

This is a minor bug in the sense that other code in the TNC does enforce the bandwidth limitations according to this table:
| Op choice | RX first | TX First |
|----|----|----|
| Low | Low -> Low | Low |
| Low | High -> Low | **HIGH** :point_left:   |
| High | Low -> Low | Low |
| High| High -> High | High |

This could cause confusion and a possible problem in the situation where the receiving side is configured for `HIGH_BANDWIDTH_MODE`. In this specific case, the stations will negotiate a high-bandwidth ARQ connection, but the originating station will only send low-bandwidth frames.

This is the relevant section in `data_handler.py`:
```python
        if static.LOW_BANDWIDTH_MODE and mode == 255:
            frametype = bytes([227])
            self.log.debug("[TNC] Requesting low bandwidth mode")
        else:
            frametype = bytes([225])
            self.log.debug("[TNC] Requesting high bandwidth mode")
```
but should be:
```python
        if static.LOW_BANDWIDTH_MODE:
            frametype = bytes([227])
            self.log.debug("[TNC] Requesting low bandwidth mode")
        else:
            frametype = bytes([225])
            self.log.debug("[TNC] Requesting high bandwidth mode")
```
A test case should be added to catch this situation in the future.

**Comment by DJ2LS** [comment]
Ah yes, I'm remembering this issue. I got feedback about this some weeks ago from a tester but already forgot it.

Thanks for fixing it, @kronenpj 🙂

We should think about removing the entire 255-stuff 🤔
