### ISSUE TITLE
"A JavaScript error occurred in the main process" after closing GUI

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#275]
An error message is thrown after closing FreeDATA GUI:

![image](https://user-images.githubusercontent.com/58949681/200253089-fe25c0b1-08ff-41a9-883a-984bf370f162.png)

Sometimes the message appears only once, sometimes the window must be closed several times in a sequence. Appears since update to 0.6.2 alpha 5.

**Comment by DJ2LS** [comment]
Problem should be fixed now. We must have a sharp eye on this to see if it occurs again.
