### ISSUE TITLE
TNC session connection establishment

### ISSUE THREAD

**Issue by pe1rrr** [DJ2LS/FreeDATA#290]
Over the next few days John G8BPQ will be setting up his pi with the latest pull to help me work on the problem I have now establishing connections to the TNC from BPQ, once that is fixed I expect to be able to continue working on the issue of connections going into perpetual loop after a connection is established. 

While heartbeat packets are sent after connection, no actual data is acknowledged or received across the connection so something is stepping out of sequence here. I’ll post more details on this issue as it develops we can hopefully help get your upcoming build out with it working.

As it is right now, shortly after testing the TNC to TNC connections Over The Air, it was clearly apparent there is a bug in the ARQ handler.

👍

**Comment by DJ2LS** [comment]
Great, @pe1rrr ! But I suggest also having a look at your network problems and why it is such delayed.  We might do this first 🤔

**Comment by DJ2LS** [comment]
Also another important point: the actual session is just a session around an arq transmission which is not that efficient. Here it would be interesting to know, which data is going to be transmitted and whats the next layer application is doing. So we could redesign the connection and making it more efficient.

**Comment by pe1rrr** [comment]
It seems that the connection doesn’t send the ‘connected’ message and jumps immediately into heartbeat mode so the TNCs will sit looping heartbeats until its force disconnected, can you confirm ?

**Comment by DJ2LS** [comment]
I can try testing tomorrow when back at home after work. The actual „normal“ behavior is, that as soon as two stations are connected, a heartbeat will be sent.Questions:- So just the network message „connected“ is missing? - Is the heartbeat packet sent too often? Should we reduce this / increasing time between heartbeats? Simon Von meinem iPhone gesendetAm 24.11.2022 um 11:08 schrieb #PacketCat Red PE1RRR ***@***.***>:﻿
It seems that the connection doesn’t send the ‘connected’ message and jumps immediately into heartbeat mode so the TNCs will sit looping heartbeats until its force disconnected, can you confirm ?

**Comment by DJ2LS** [comment]
> It seems that the connection doesn’t send the ‘connected’ message and jumps immediately into heartbeat mode so the TNCs will sit looping heartbeats until its force disconnected, can you confirm ?

Added more connection messages, available with next release

**Comment by DJ2LS** [comment]
@pe1rrr maybe there are some issues, but I had to merge the corresponding PR. I'm reopening this

**Comment by DJ2LS** [comment]
@pe1rrr meanwhile some bugs have been fixed ( again 😄 ) - does the problem still exists?

**Comment by DJ2LS** [comment]
no answer yet. @pe1rrr feel free reopening this if it still exists
