### ISSUE TITLE
SSID: use base Callsign (AA0AA-0 -> AA0AA) for better readability

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#296]
In regard to the readability, I´d propose the usage of a base callsign without SSID (in case a user uses the default SSID -0 only).

So this means, that internally (protocol) the SSID -0 is always processed as any other SSID, but in the external presentation (e.g. in the chat and in the lastheard list), only the base callsign is displayed. Just for -0. Any other SSID´s should display as they already do.

**Comment by DJ2LS** [comment]
@Mashintime any idea how we could do this inside GUI?
Maybe doing a Callsign check and stripping Callsign if SSID == -0 ?

**Comment by Mashintime** [comment]
Sure it'd be easy to do, but would require extensive testing to ensure it doesn't break anything.

**Comment by DJ2LS** [comment]
We could implement this into new gui. Keeping the SSID always attached in background but just change the displaying. 

When opening a new chat without attaching the SSID we should attach "-0" in background
