### ISSUE TITLE
Invalid locator format leads to explorer crash

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#304]
Someone specifying a locator in an invalid format will cause explorer.freedata.app to crash (will no longer show any stations):

![128f0bb225ee93d371abf692239e6af108947665148ae8ebdc5aaf217d6a5ced](https://user-images.githubusercontent.com/58949681/209156135-eb6e6149-0f43-41bc-b8fa-7be9d482c9b1.png)

**Comment by DJ2LS** [comment]
should be fixed now
