### ISSUE TITLE
retry failed connection

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#319]
Steps:

- On a failed transmission 
    - IRS stores already received data to buffer --> Now we know our buffer position
    - IRS stores crc information to buffer --> that's the minimum requirement, a fully received data header with crc information

- Next transmission:
    - ISS send channel opener
    - IRS send channel opener and buffer position (32bit int) and checksum (crc32) = 8bytes
    - ISS checks if these information are available against "0", then compares crc with own crc of data which will be sent. If equal override buffer position minus some bytes, depending on speed level,  which will be used as indicator for IRS, that we are continuing ( data will be overwritten in buffer then )
    - If we can continue, copy stored buffer to actual transmission buffer and erase stored buffer

**Comment by pe1rrr** [comment]
I am following all of this by email,  I don’t meant to patronise. Genuinely blown away with how much you have been putting in over Christmas. Really cool.

**Comment by DJ2LS** [comment]
Not sure, if we need this, as auto retrying the entire message might be more stable

**Comment by DJ2LS** [comment]
Closing this one as it's making more sense retrying entire data triggered by beacon
