### ISSUE TITLE
---- GUI optimizations and features ----

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#331]
## Main
- [x] Display tnc ip in title 
- [x] Reduce progressbar CPU load -> move to chartjs 
- [x] Move to Vue framework 
- [x] Make waterfall color adjustable 
- [x] Waterfall optimisations 
- [x] Simplify code by using more functions 
- [x] Use electron progress bar 
- [x] Show version mismatch correctly 
- [x] Move progressbar of transmission to tnc-message instead of state message 
- [x] Notification in settings to restart the tnc 
- [x] Remove Scrollbar from splash screen 
- [x] Disable ping and CQ button when pressed, then show a spinner
- [x]  List of contributors and testers
- [ ] low cpu mode for chat
- [x] #357
- [x] show callsign we are connected to
- [x] nicer alerts https://dribbble.com/shots/12734316-Toast-Notification
- [x] STOP button not self explaining enough maybe "STOP TRANSMISSION?"
- [x] add strength/meter progress bar next to dBFS
- [ ] maybe remove tnc state IDLE/BUSY button?
- [x] add time left progress bar somewhere, maybe part of transmission progress bar as double progress bar
- [x] add c2 detection next to "channel busy indicator"
- [x] display ping ACKs in chat
- [x] https://github.com/DJ2LS/FreeDATA/issues/264
- [ ] https://github.com/DJ2LS/FreeDATA/issues/268
- [ ] https://github.com/DJ2LS/FreeDATA/issues/296
- [ ] https://github.com/DJ2LS/FreeDATA/issues/178
- [ ] https://github.com/DJ2LS/FreeDATA/issues/140
- [ ] https://github.com/DJ2LS/FreeDATA/issues/60
- [x] fix send on enter not working always
- [ ] add encrypted bridge to remote.freedata.app service
- [x] https://github.com/DJ2LS/FreeDATA/issues/338
- [x] https://github.com/DJ2LS/FreeDATA/issues/341
- [x] #363
- [x] Frequency not changed anymore on change
- [x] add on/off switch for audio auto tune
- [x] add on/off switch for publishing transmission stats

## Chat 
- [x] Show ping in chat
- [ ] Drag and drop 
- [ ] Image preview
- [ ] Image small preview for all images 
- [ ] Optimise code structure 
- [ ] Voice messages 
- [ ] Quote messages 
- [ ] Sign messages 
- [ ] Send location with map view 
- [ ] Save message as ADIF log 
- [x] Fix Charts error
- [x] Remove single message from database
- [x] #364
- [ ] Shared folders / request folder list from other station and request them
- [x] Status messages, can be requested
- [x] Avatars, can be requested
- [x] Fix error for "action-update-transmission-status" when receiving transmission status while transmitting and "no-uuid"

**Comment by Mashintime** [comment]
Thanks for taking the time to create this list.

**Comment by DJ2LS** [comment]
https://www.npmjs.com/package/browser-image-compression

**Comment by DJ2LS** [comment]
- [ ] low cpu mode for chat
- [ ] fix version and callsign on title for ubuntu 
- [ ] show callsign we are connected to
- [ ] display ping ACKs in chat
- [ ] https://github.com/DJ2LS/FreeDATA/issues/264
- [ ] https://github.com/DJ2LS/FreeDATA/issues/268
- [ ] https://github.com/DJ2LS/FreeDATA/issues/296
- [ ] https://github.com/DJ2LS/FreeDATA/issues/178
- [ ] https://github.com/DJ2LS/FreeDATA/issues/140
- [ ] https://github.com/DJ2LS/FreeDATA/issues/60
- [ ] fix send on enter not working always

**Comment by DJ2LS** [comment]
@Mashintime feel free checking the already working features

**Comment by Mashintime** [comment]
@DJ2LS Are you good with marking the progress bar CPU as done?

**Comment by DJ2LS** [comment]
@Mashintime yes. We've made minor improvements in this area. Adjustments can be implemented at every time

**Comment by jpronans** [comment]
What about "Sorting function for Heard Station List". I.e sort be last heard, callsign, distance or SNR?

**Comment by DJ2LS** [comment]
> What about "Sorting function for Heard Station List". I.e sort be last heard, callsign, distance or SNR?

implemented

**Comment by DJ2LS** [comment]
@Mashintime could you check the list above and check the ones we/you already implemented?
