### ISSUE TITLE
alc auto tune

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#350]
ALC auto-tune feature:
checking for ALC  - if too low, increase audio level

Todo: check why audio level is str and not int

**Comment by DJ2LS** [comment]
Latest state is, audio level will be reduced to total silence...bad..needs a fix

**Comment by DJ2LS** [comment]
In general this is a tricky feature as it depends on hamlib. So I'm not sure about the effort we should spend for this...
@dk5sm @LA3QMA  @Mashintime what do you think about this?

**Comment by LA3QMA** [comment]
I guess this is a tricky part. i-e Elecraft KX3 requires the ALC to be 4-5 in digimodes and regular mode its 0.
It also have two different DIG modes.

Not sure how hamlib support this on different radios.

Can we use a different approach to get the same result?
i.e transmit a tone and increase the level and then read the power out?

**Comment by DJ2LS** [comment]
It feels a bit like we should remove this feature as it's causing more problems. Better working on a reliable tuning mechanism

**Comment by jpronans** [comment]
Maybe with some defaults for known/tested radios?

**Comment by DJ2LS** [comment]
I also tend to remove this feature as it’s really depending on the corresponding radio. Von meinem iPhone gesendetAm 03.03.2024 um 20:39 schrieb John Ronan ***@***.***>:﻿
Maybe with some defaults for known/tested radios?
