### ISSUE TITLE
Revoke message - remote delete

### ISSUE THREAD

**Issue by Mashintime** [DJ2LS/FreeDATA#364]

**Comment by Mashintime** [comment]
I don't think is something we should do.  A station who could hear both sides of the conversation could be a bad actor and do this.  We would need some way of verifying a remote station is really who they say they are.

**Comment by DJ2LS** [comment]
Yea, message signing is an important area somewhen. Not sure how to realise this efficient

**Comment by DJ2LS** [comment]
@Mashintime @dk5sm  I'm in general not sure if this feature would work that well for HF. Even with message signing. What do you think? Should we close this issue/feature?

**Comment by DJ2LS** [comment]
@Mashintime with message signing enabled, we could now work on this I think.

on ISS:
-- Additional button next to message: "revoke"
-- Change color of message and make the message itself filled with placeholders so its clear its revoked
-- find a way of making sure, the revoke command has been sucessfully transmitted to IRS

on IRS:
-- check if message is signed
----- if yes, mark message as revoked and make it filed with text placeholders
----- if no, do nothing and ignore command

**Comment by DJ2LS** [comment]
I think we should close this one, @Mashintime  

Not sure if it's an good idea doing this as it can cause some trouble. Also message signing would be needed. But this needs to be implemented first
