### ISSUE TITLE
Frequency control display broken (0.8.0-a.1, Windows)

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#373]
After starting the TNC, the frequency control section shows like this - either frequency and/or mode not showing up:

![image](https://user-images.githubusercontent.com/58949681/224530109-6fa8c791-0fd2-4bc3-a8a2-8ec223c6ff91.png)
![image](https://user-images.githubusercontent.com/58949681/224530175-6c817db1-02e3-41bf-b09f-e0de8ea8d39d.png)

Setting frequency or mode manually is working fine, but it seems that reading out does not work:
![image](https://user-images.githubusercontent.com/58949681/224530224-7f074183-dd13-405d-b541-ae0bb61ab394.png)

The behavior was observed under Windows only.

**Comment by Mashintime** [comment]
This info comes from the TNC to the GUI.  I'd guess we'd need to figure out whether it's the tnc or hamlib.  Did you observe the issue with previous versions of FD?

Maybe ensure you have the latest hamlib and/or running manually rigctld with -vvvv and other args needed for FD

**Comment by DJ2LS** [comment]
If it's a version related issue we need to update docs.

I'm running Hamlib 4.4 or so and it's working fine on Ubuntu. Question is, if we can reproduce this with latest Hamlib on Ubuntu as well.

**Comment by dk5sm** [comment]
I do not notice this problem on Ubuntu as well. But it´s reproduceable on mine and another Windows-Box. On both machines hamlib is running in version 4.5.4. Same hamlib version used with the previous FD version 0.7.1 / 0.7.2 / 0.7.3 - but without this issue.
We had a similar gui/hamlib issue before. Maybe an unmatched dependency?

**Comment by Mashintime** [comment]
I don't experience this issue with 4.5.4 on Windows.  Are both windows boxes using the same transceiver/interface?

**Comment by dk5sm** [comment]
No. I am using an IC-705 and on the other machine an IC-7300 is attached. Both via USB-cable.

**Comment by dk5sm** [comment]
![image](https://user-images.githubusercontent.com/58949681/224564962-7149b3d6-61e2-40f8-a043-6752c2f08b9a.png)

I am running rigctld as a windows service on both machines, but running it on the commandline makes no difference.  However, hamlib´s console is throwing an error in an endless loop - "rig_powerstat is not on = 0". Maybe this is a hint?

**Comment by DJ2LS** [comment]
Might be the receiving of power status? Introduced with ALC level. That’s the only thing changed in this version Von meinem iPhone gesendetAm 12.03.2023 um 19:34 schrieb Stefan DK5SM ***@***.***>:﻿

I am running rigctld as a windows service on both machines, but running it on the commandline makes no difference.  However, hamlib´s console is throwing an error in an endless loop - "rig_powerstat is not on = 0". Maybe this is a hint?

**Comment by DJ2LS** [comment]
Tested on Windows 11 with rigctld 4.5.4 and "dummy" device ( rigctld -m 1 )

@dk5sm could you do me the favour and checking if the problem also occurs with a dummy device?

**Comment by dk5sm** [comment]
Sorry, I can´t reproduce the error using the dummy device.

**Comment by Mashintime** [comment]
I was able to reproduce on windows with an ic-705.  I think the timeout is occurring too quickly and rigctld can't return the data quickly enough.

Changing the timeout value on line 162 in rigctld.py seems to fix it, but not sure if there might be a better way.

>>self.data_connection.settimeout(0.25)

**Comment by frspin** [comment]
Same problem here with Ubuntu 22.04
I am starting rigctld before starting FD with a shell proc.
In Ubuntu 22.04 rigctld is 4.3.1
When FD start there is no info in frequency and in mode fields.
Only after typing a frequency frequency field is populated.

Franco Spinelli
IW2DHW

**Comment by Mashintime** [comment]
Please checkout qm-373 branch, it should fix this issue.

https://github.com/DJ2LS/FreeDATA/tree/qm-373

**Comment by DJ2LS** [comment]
Should be fixed, @dk5sm , if so, please close this issue
