### ISSUE TITLE
Auto-Connect TRX after startup

### ISSUE THREAD

**Issue by dominik0815** [DJ2LS/FreeDATA#385]
After startup the software it is needed to hit button "Start" in "TNC RIG CONTROL"-Window for usage of Hamlib-Connected devices. It would be nice to tick some option to autoconnect after startup.

**Comment by Mashintime** [comment]
Should be doable, will see what I can do.

**Comment by DJ2LS** [comment]
@dominik0815 if the feature fits to your needs, please drop a line so we can close this feature request
