### ISSUE TITLE
digirig

### ISSUE THREAD

**Issue by seydunatirej** [DJ2LS/FreeDATA#398]
Hi. Very cool application. I am curious. have you ever tried to run it with digirig?

**Comment by DJ2LS** [comment]
Hi @seydunatirej , yes digirigs should be supported, but we need to gather more experience here. Have you seen our discord server? We have at least two person ( me included ) owning digirigs . That's a good place for asking.

**Comment by seydunatirej** [comment]
I don't use Discord, but I want to make the program with digirig so i will take look at Discord. Thank you!

**Comment by DJ2LS** [comment]
@seydunatirej because of the fact you're getting help on Discord I'm closing this one. Feel free opening further issues if you find bugs or something else.
