### ISSUE TITLE
"Auto-start TNC/rigctld" deletes settings for Hamlib-Port-Definition

### ISSUE THREAD

**Issue by dominik0815** [DJ2LS/FreeDATA#402]
After I activvated Auto-Connection and restart FreeData, Hamlib-Port-Definition is cleared and transceiver is not connected automatically. I think, Feature is working (I seen that rigctrld is trying to connect), but I think without the port definition it could not find connection.
![Before activate Auto-Connect](https://user-images.githubusercontent.com/64140671/233826596-6681b4a2-2228-48bc-b122-637449d8473a.png)
![After activate auto-connect and restart software (Rig is not corrected)](https://user-images.githubusercontent.com/64140671/233826595-7edaa7f8-a357-4c23-bfdf-ffc1bdd2b335.JPG)

**Comment by DJ2LS** [comment]
Duplicate with #407
