### ISSUE TITLE
Can we store the chart with the file transfers in the chat, please?

### ISSUE THREAD

**Issue by g0hww** [DJ2LS/FreeDATA#403]
It would be nice if we could review the charts for completed transfers, in the chat window.
Perhaps a button for each send and receive.
We could either store images, or raw data.
The info could be deleted when the transfer is deleted from the chat window, either individually or by deleting the entire chat history for that station.

**Comment by Mashintime** [comment]
It would be nice, yes.  But the time commitment to implement and test I don't think is warranted at this time.

**Comment by DJ2LS** [comment]
we could save the information to the database for each message, but only requesting it when opening the chart. With the new gui this might be easier I think. 
We could add an "info button" next to each message, opening a modal then and displaying the chart. On clicking the info button, we are requesting the chart information from the database.

**Comment by DJ2LS** [comment]
Will be implemented in new gui. Some more small steps and it's available

**Comment by DJ2LS** [comment]
![grafik](https://github.com/DJ2LS/FreeDATA/assets/75909252/0503ae52-0b56-47d5-a3d1-8309cf239229)
