### ISSUE TITLE
Finish TCI support

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#420]
We need to finish implementation of TCI so it's at least controllable via GUI.

Todos:
- [ ] Add TCI field next to Hamlib 
- [ ] Add Startup via Daemon
- [ ] Change Hamlib related functions to "radio" related function and variable names

**Comment by DJ2LS** [comment]
duplicate

**Comment by Mashintime** [comment]
Does TCI use hamlib/rigctld, or does it work without hamlib?
