### ISSUE TITLE
Problems with Ubuntu 22.04

### ISSUE THREAD

**Issue by frspin** [DJ2LS/FreeDATA#456]
Version 0.10.0-alpha.2 (latest) is not working with my Ubuntu 22.04 running it also from Appimage

I start  rigctld with a shell proc. 
This is my proc:
`
rigctld -m 1043 -r /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A907OEFM-if00-port0 -s 38400 &
cd tnc
python3 daemon.py&
pid=$!
echo $pid
cd ../gui
npx electron main.js
kill $pid
killall rigctld
`
Gui is started but there is an error:

11:02:53.216 (tnc)                › TNC connection error

TNC don't start and also PTT test don't work

Running Appimage don'show this error but no waterfall, no PTT test

I also can start main.py in tnc directory:

`rigctld -m 1043 -r /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A907OEFM-if00-port0 -s 38400 &
cd tnc
python3 main.py --use-config config_ft897.ini&
pid=$!
echo $pid
cd ../gui
npx electron main.js
kill $pid
killall rigctld
`

and, with this (no daemon running) there are no errors but no PTT control and no waterfall

In all test rigctld is connected, frequency and mode are correctly shown and beacons are received.
Version 0.9.X was OK

Franco Spinelli
IW2DHW

**Comment by frspin** [comment]
Update on further test.

Removed ~/.config/FreeDATA folder and restarted all.
Reconfigured and now 0.10.0-alpha.2 is running.

I don't know how is changed in config files. Apparently nothing!

Franco Spinelli
IW2DHW

**Comment by DJ2LS** [comment]
first aid (for alpha/beta testers) | FreeDATA Wikiwiki.freedata.appVon meinem iPhone gesendetAm 06.07.2023 um 12:03 schrieb frspin ***@***.***>:﻿
Update on further test.
Removed ~/.config/FreeDATA folder and restarted all.
Reconfigured and now 0.10.0-alpha.2 is running.
I don't know how is changed in config files. Apparently nothing!
Franco Spinelli
IW2DHW

**Comment by frspin** [comment]
Command as suggested in "first aid (for alpha/beta testers) are the first command executed many other times.
But, in this case, a complete remove of config directory was required.

Add a new (4) point to first aid: remove config and reconfigure.

Franco Spinelli
IW2DHW

**Comment by DJ2LS** [comment]
Thanks Franco, I added a point 4 to the wiki. 

Closing this issue as it seems to be solved.
