### ISSUE TITLE
unread message counter resests only when clicked N times where N = recevied messages

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#465]
unread message counter resests only when clicked N times where N = recevied messages

**Comment by Mashintime** [comment]
The unread message counter (the RF chat button on the main interface) is on a timer and only updates every 10-15 seconds.  Is it possible this is the problem.

I'll verify it's working correctly on my end as well.

**Comment by DJ2LS** [comment]
Deprecated because of new gui
