### ISSUE TITLE
Audio output level in dB

### ISSUE THREAD

**Issue by manoode** [DJ2LS/FreeDATA#469]
I purchased a new radio wich is attached directly to the (USB) soundcard of the Mini-PC.
Though JTDX and VARA can toggle the PTT via VOX, FD can't not even when setting the TX Level to maximum (250).

The Audio TX level should be measured and controlled analog to other programs like JTDX/XSJTX and VARA. The scale there is in dB.

**Comment by Mashintime** [comment]
You can try the tune button to increase audio output, as well as your operating system's volume mixer to increase audio output.

**Comment by DJ2LS** [comment]
Implemented in new version
