### ISSUE TITLE
S-Meter in GUI not display information for some TRX

### ISSUE THREAD

**Issue by sp2ong** [DJ2LS/FreeDATA#470]
It looks like some transceivers not support information used to display on GUI S-Meter. For example, ICOM-706 with hamlib v4.6 (from github sources) not display any data in S-Meter. The FreeData version is 0.10.2-alpha.1.
As Simon DJ2LS wrote on discord, it is worth adding "not supported" display information in the GUI

**Comment by DJ2LS** [comment]
We should add this to the new gui.
 @Mashintime maybe an easy topic for you?

**Comment by Mashintime** [comment]
Already in vuejs version; will show unsupported if value is "".

**Comment by DJ2LS** [comment]
Ah nice, then I'm going to close this one.
