### ISSUE TITLE
radio connection problem

### ISSUE THREAD

**Issue by Svetlin19777** [DJ2LS/FreeDATA#479]
The program is very buggy. everything sucks. does not want to connect to a transmission for ic-7600. From version Free DATA-Setup-0.8.1-alpha upwards does not find the sound or usb ports in any way.
I use windows 10 x64.

**Comment by DJ2LS** [comment]
Hi @Svetlin19777 , thanks for taking the time and opening an issue! I understand, you're possibly frustrated, but your wording and topic description are not helping that much. Also the software is still an alpha. So errors are common. 

Did you have a look at the wiki, specially here: https://wiki.freedata.app/en/usage/gui-config-and-logging-files ? 

Also please try deleting the config folder and then starting the app again. 

If you need help in any case, free free asking on our discord channel: https://discord.gg/Zgqd7hrTtD


Thanks, Simon

**Comment by Svetlin19777** [comment]
Thanks for the email. My description is not good because my English is not
good. I'm sorry. I got to know everyone about the program and the launch.
Including additional radio tuning program. But from the version I
specified, it doesn't want to find the sound cards and usb ports.
Apparently the registry it creates on my computer stays somewhere. I dont
know where. And the settings are transferred automatically when running a
version. This creates a problem. I followed the setup method step by step.
Only once was it able to drive my IC-7600 radio to transmit. It was on some
old version. So there is hope. :)

На сб, 30.09.2023 г., 19:46 ч. DJ2LS ***@***.***> написа:

**Comment by Svetlin19777** [comment]
Hello again.
Today I was able to set up the program to connect to my ic-7600 radio. I am
sending photos of the settings showing the version the radio is running. I
note that I had to run the program several times until the test button
turned green. There is a problem in this direction and it needs to be
worked on.
Good luck!

На пн, 2.10.2023 г. в 9:01 ч. Svetlin Nikolov ***@***.***>
написа:

**Comment by Svetlin19777** [comment]
noting audio devices for this version

На пн, 2.10.2023 г. в 13:41 ч. Svetlin Nikolov ***@***.***>
написа:

**Comment by Svetlin19777** [comment]
На пн, 2.10.2023 г. в 14:05 ч. Svetlin Nikolov ***@***.***>
написа:

**Comment by Svetlin19777** [comment]
interesting, i pressed the stop button and the ports appeared.

На пн, 2.10.2023 г. в 14:07 ч. Svetlin Nikolov ***@***.***>
написа:

**Comment by Svetlin19777** [comment]
[image: image.png]

На пн, 2.10.2023 г. в 14:19 ч. Svetlin Nikolov ***@***.***>
написа:

**Comment by DJ2LS** [comment]
Hi, @Svetlin19777 no worries about your english skills! I'm actually reworking the GUI, so this needs to be tested again then as soon as the new gui is published. THe old one has several problems. 

FOr performancy reasons, the "daemon" which is gathering the audio device information is only working, while tnc is stopped.

**Comment by DJ2LS** [comment]
I'm closing this, as its deprecated because of work on new gui
