### ISSUE TITLE
Hardcoded value.

### ISSUE THREAD

**Issue by LA3QMA** [DJ2LS/FreeDATA#481]
Reminder that this hardcoded value should be solved.

https://github.com/DJ2LS/FreeDATA/blob/4349c5f013ea0066f51eb3e9fdb54a61878aca91/tnc/data_handler.py#L3227C13-L3227C14

**Comment by DJ2LS** [comment]
As a hot fix we could ignore Callsign data from the default hardcoded one within gui Von meinem iPhone gesendetAm 01.10.2023 um 19:45 schrieb Kai Günter Brandt ***@***.***>:﻿
Reminder that this hardcoded value should be solved.
https://github.com/DJ2LS/FreeDATA/blob/4349c5f013ea0066f51eb3e9fdb54a61878aca91/tnc/data_handler.py#L3227C13-L3227C14

**Comment by DJ2LS** [comment]
implemented into VueJS GUI
