### ISSUE TITLE
if we are receiving a codec2 signal, add bonus time to timeout

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/FreeDATA#482]
if we are receiving a codec2 signal but can't decode the entire burst, add bonus time to timeout. Combined with shorter burst intervals, we might increase decoding chance

**Comment by Mashintime** [comment]
Already implemented, though delay may need some tweaking.

https://github.com/DJ2LS/FreeDATA/commit/19697da88b9a789f9a6d766a31ecf31854e41cc3
