### ISSUE TITLE
Package dependencies on Raspberry Pi for emojis

### ISSUE THREAD

**Issue by deejdeej** [DJ2LS/FreeDATA#485]
To get the emojis to appear correctly in the chat sessions on a Raspberry Pi, install the package:
fonts-noto-color-emoji

Raspberry Pi OS 11 (bullseye) and Raspberry Pi OS 12 (bookworm)

(Edited to remove "node-emoji" and "node-emojis-list" packages that aren't needed)

**Comment by deejdeej** [comment]
@DJ2LS They are needed in Raspberry Pi OS 11 which most people are likely running today.  Raspberry Pi OS 12 just came out 2 weeks ago and I haven't had a chance to try it yet.

**Comment by DJ2LS** [comment]
I'm not sure about the node-emojis-list dependency

**Comment by DJ2LS** [comment]
fonts-noto-color-emoji cant be found on desktop systems

**Comment by DJ2LS** [comment]
@deejdeej can you test with @electron-fonts/noto-color-emoji ?

**Comment by deejdeej** [comment]
I'm running the 64 bit "Raspberry PI OS with desktop" version for both 11 and 12.  An "apt install fonts-noto-color-emoji" works on both.

Can you explain what you mean by "fonts-noto-color-emoji cant be found on desktop systems" ?

**Comment by DJ2LS** [comment]
@deejdeej do we have a actual status on this?

**Comment by deejdeej** [comment]
"apt install fonts-noto-color-emoji" works on both Raspberry Pi OS 11 and 12, and I have verified this package is needed for the emoji fonts to display correctly in the FreeDATA GUI.
