### ISSUE TITLE
Explorer: have active stations be above old ones.

### ISSUE THREAD

**Issue by starvald** [DJ2LS/FreeDATA#511]
In the explorer is it possible to set newer signals to be above older ones, i was testing my sdr on 20m with a SWL handle so it shows gray being old connection but as i'm on 11m now and active with my rig the old gray one sits on top of it.

only shows up if i toggle off 20m, as all of them on is the default in explorer you wouldn't know i was there.

**Comment by DJ2LS** [comment]
Intention was, using https://leafletjs.com/plugins.html#clusteringdecluttering

**Comment by DJ2LS** [comment]
@Mashintime and another explorer related topic

**Comment by Mashintime** [comment]
Marking as closed; was implemented late last year.
