### ISSUE TITLE
Alpha 0.11.0 -> 0.11.1a no longer detecting audio devices, hamlib

### ISSUE THREAD

**Issue by baitisj** [DJ2LS/FreeDATA#553]
**Describe the bug**
After testing various AppImage releases, changes made in FreeDATA-0.11.1-alpha.1.AppImage no longer detects audio devices or hamlib 

**To Reproduce**

Starting with Alpha 0.11.1-alpha.1 thorough alpha.3, neither audio devices nor Hamlib are detected and the modem cannot be started.
If I use  FreeDATA-0.11.0-alpha.8.AppImage and earlier, the application works as expected.

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.3 LTS (Jammy)
- Platform: Desktop x86-64

**Comment by Mashintime** [comment]
Hello, we're currently in the process of a major overhaul of FD and thus not will not spend time on the older code base.  We hope to have this newer version available soon and we appreciate your patience.
