### ISSUE TITLE
Please allow 11m callsigns

### ISSUE THREAD

**Issue by linux150** [DJ2LS/FreeDATA#658]
Callsign not allowed, is it possible to allow cb calls like 35TM150

lg
martin

**Comment by DJ2LS** [comment]
hi @linux150 , oh, we should add this again! Seems this one got lost while rewriting the code!

**Comment by linux150** [comment]
would be fine, thanks 73

**Comment by DJ2LS** [comment]
It's on our todo list now, but please give us some time

**Comment by DJ2LS** [comment]
https://github.com/DJ2LS/FreeDATA/pull/657/commits/0349cf1b7c2a6a26b99966b26c80859c7fa70c22 might already fix this...

**Comment by linux150** [comment]
Perfect, ready to close !
