### ISSUE TITLE
Locator 6 digits!!! Dont allow 4 digits

### ISSUE THREAD

**Issue by linux150** [DJ2LS/FreeDATA#661]
Please check the entry of 6 digit, we searched long time why cq is not working and found out our friend has only entered 4 digits in locator settings. It should not be allowed 

thanks

**Comment by DJ2LS** [comment]
A ticket already exists on our internal todo lists. We will fix this somewhen with next releases Von meinem iPhone gesendetAm 22.02.2024 um 16:56 schrieb linux150 ***@***.***>:﻿
Please check the entry of 6 digit, we searched long time why cq is not working and found out our friend has only entered 4 digits in locator settings. It should not be allowed
thanks

**Comment by DJ2LS** [comment]
Should be handled / fixed with next release
