### ISSUE TITLE
Radiocontrol via HamRadio deluxe

### ISSUE THREAD

**Issue by linux150** [DJ2LS/FreeDATA#662]
Would be nice, because i use it for all other digimodes too with portsplitter. Now working with flrig but HRD would be nice.

73
Martin

**Comment by DJ2LS** [comment]
Martin, do you have any further information about hrd radio server and the corresponding api?

**Comment by linux150** [comment]
Sorry, not really
Js8call is opensource and work with HRD.
Maybe Irad will also use it on VarAc, but not programmed until yet.
73

**Comment by DJ2LS** [comment]
I contacted HRD, FYI

**Comment by DJ2LS** [comment]
still no response from HRD

**Comment by DJ2LS** [comment]
Contacted HRD again

**Comment by DJ2LS** [comment]
got a response
result: they lost the api documentation, I should check the WSPR source code. 

To me it seems, it's not making sense, continuing with this as long as there is no interest of HRD.

**Comment by linux150** [comment]
ok thank you for your answer
73
