### ISSUE TITLE
explorer.freedata.app - 6m reporting is missing

### ISSUE THREAD

**Issue by LA3QMA** [DJ2LS/FreeDATA#664]
Add filter for 6m band to the explorer.freedata.app

![image](https://github.com/DJ2LS/FreeDATA/assets/2430634/716b3f35-6364-4e3d-9e7c-bf1b7de49117)

**Comment by DJ2LS** [comment]
@Mashintime are you interested in doing this? Should'nt be too hard I guess.

**Comment by Mashintime** [comment]
I'll work on this this evening.
