### ISSUE TITLE
ValueError: RIGCTLD.port must be <class 'int'>. '18001' <class 'str'> given.

### ISSUE THREAD

**Issue by Mihara** [DJ2LS/FreeDATA#672]
**Describe the bug**

I am using a systemwide `rigctld` on an unexpected port. Attempting to set it through the GUI results in the GUI blanking out, becoming unresponsive, and an error message in the server terminal:

```
ValueError: RIGCTLD.port must be <class 'int'>. '18001' <class 'str'> given.
```

Looks like you missed a parseInt somewhere.

**Comment by DJ2LS** [comment]
thanks for the bug report, @Mihara I just pushed a fix to this. Should be available with next release
