### ISSUE TITLE
modemport fixed or defined by user?

### ISSUE THREAD

**Issue by frspin** [DJ2LS/FreeDATA#674]
Is modemport setting in config file for modem used?
It seem that 5000 as port is fixed and value in config file ignored.

Is this correct?
If is fixed we can not have different modem on different rig at the same time.

Regards

Franco Spinelli
IW2DHW

**Comment by DJ2LS** [comment]
hi @frspin the modem port should be adjustable, but there are some problems actually occuring with this. We will fix this from time to time.

**Comment by frspin** [comment]
Il 04/03/24 14:55, DJ2LS ha scritto:
> hi @frspin <https://github.com/frspin> the modem port should be 
> adjustable, but there are some problems actually occuring with this. We 
> will fix this from time to time.

Ok
I will wait for this.

Please keep me informed on fix

Franco Spinelli
IW2DHW

**Comment by DJ2LS** [comment]
please check the message I've sent you via HF ;-) 

the "develop" branch contains latest changes
