### ISSUE TITLE
Can't find the sound card.

### ISSUE THREAD

**Issue by pepefrog1234** [DJ2LS/FreeDATA#676]
**Describe the bug**
Can't find the sound card.

**To Reproduce**
1.Install the latest version
2. Go to the modem settings page
3. The sound card does not appear in the sound card drop-down menu.

**Expected behavior**
Find the sound card that your computer currently has.

**Logfiles**
https://wiki.freedata.app/en/usage/logging

**Screenshots**
![螢幕截圖 2024-03-07 13 06 24](https://github.com/DJ2LS/FreeDATA/assets/32506473/35a0a136-447f-4b31-8391-5bb261692318)

**Desktop (please complete the following information):**

- OS: Windows
- Version 10

**Comment by DJ2LS** [comment]
@pepefrog1234 thanks for the report! Which FreeDATA are you running?

**Comment by pepefrog1234** [comment]
0.14.1

**Comment by DJ2LS** [comment]
Mh, this should have been improved with this version.
You are running the Windows installer, right?

On first start after installation FreeDATA needs some seconds, maybe waiting ten seconds, does the problem still exist?

**Comment by pepefrog1234** [comment]
My computer is running windows 10. I reopened the software and waited, the problem still exists.

**Comment by DJ2LS** [comment]
mh, this should occur, 

@Mashintime @dk5sm do you have the time, reproducing this? 

@pepefrog1234 is this the first time running FreeDATA?

**Comment by pepefrog1234** [comment]
This is not the first time I have opened the program

**Comment by DJ2LS** [comment]
@pepefrog1234 did you start the server? I see the network connection is red

**Comment by dk5sm** [comment]
Please also check the modem port within config.ini; it should be 5000. Sometimes you can still find 3050 in it as a legacy.

**Comment by pepefrog1234** [comment]
> connection
No I didn't start the server, is that the problem?

**Comment by pepefrog1234** [comment]
> Please also check the modem port within config.ini; it should be 5000. Sometimes you can still find 3050 in it as a legacy. 

Okay, I'll check.

**Comment by DJ2LS** [comment]
Yea I think so. But the latest installer should provide everything and you just have tk start the gui and the server should start automatically

**Comment by pepefrog1234** [comment]
> Yea I think so. But the latest installer should provide everything and you just have tk start the gui and the server should start automatically 

Thanks to the development team, I've solved it.
