### ISSUE TITLE
Map widget

### ISSUE THREAD

**Issue by SpudGunMan** [DJ2LS/FreeDATA#710]
An explorer like map widget displaying nodes without internet (points with grid on map)

**Comment by DJ2LS** [comment]
Thanks, @SpudGunMan I like this feature request, have been thinking about this as well many times. 
I'm stuck with finding a nice offline map which saves implementation time.

@Mashintime what do you think? As a start we could implement a simple map, showing heard stations for example. But core requirement in my opinion is a nice offline map, maybe a vector map or so, bot based on images 🤔

**Comment by DJ2LS** [comment]
![Bildschirmfoto vom 2024-09-11 20-49-19](https://github.com/user-attachments/assets/a090b475-8e5e-418e-b00a-413fd958637c)
