### ISSUE TITLE
Chat window tile needs a scroll bar

### ISSUE THREAD

**Issue by SpudGunMan** [DJ2LS/FreeDATA#747]
### FreeDATA Version

Dev

### What operating system are you using?

Other (specify below)

### Operating System Version

Mint

### Architecture

x64

### Area of problem

GUI

### Describe the bug

On the chat window, the left tile holds all the “chat bubbles” when full no scroll bar shows up. So the chats are inaccessible due to objects exceeding boundary, adding a verticle scroll would correct this 

### To Reproduce

Have a bunch of chat sessions to fill up your available space in the window (likely could also shrink the main app down in size and experience same) 

### Expected behavior

Scroll bar to access objects out of reach

**Comment by DJ2LS** [comment]
fixed in develop
