### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LA3QMA** [DJ2LS/FreeDATA#749]
### FreeDATA Version

0.16.0

### What operating system are you using?

Windows

### Operating System Version

win11

### Architecture

x64

### Area of problem

Installation

### Describe the bug

App doesnt work the first time after installation. Close and restart and its working as expected.

when started it first reported "invalid input device index 5a1c and this is ok i guess. then i get the list with all sound devices in the GUI. then in the cmd i get all info about gui available on http etc. and lotz of API get/post info. then a error

First image shows the error after the GUI is opened.
Second image shows error after closing the server using ctrl+c

### To Reproduce

Install using windows installer then start the app.

### Expected behavior

Should start without error.

### Screenshots

![fd_error2](https://github.com/user-attachments/assets/9e3160c0-9b0d-4680-802c-dd01c67fa068)
![FD_error1](https://github.com/user-attachments/assets/97adbaea-b173-46c6-9a36-55a88c0cfca5)

**Comment by DJ2LS** [comment]
@LA3QMA thanks, I probably fixed this. Now restarting modem on first start should work as well
