### ISSUE TITLE
[Feature Request]: Allow speed readout units to be changed to bits per second (like in VARA) if desired

### ISSUE THREAD

**Issue by Glitch31415** [DJ2LS/FreeDATA#763]
### Problem Description

The current unit is bytes per minute, which may be more practical, but I'm used to the technical display of VARA, showing the bits per second directly from the modem.

### Proposed Solution

Add a toggle in the settings to switch the speed units from "bytes per minute (bpm)" to "bits per second (bps)". Read the bps directly from the modem.

### Alternatives Considered

None

**Comment by DJ2LS** [comment]
https://github.com/DJ2LS/FreeDATA/pull/776/commits/1224a74621f3d151f40ff621b1fd21d9f7726ca0 added bits per second statistics to server
