### ISSUE TITLE
[Feature Request]: compressing and resizing images

### ISSUE THREAD

**Issue by LA3QMA** [DJ2LS/FreeDATA#784]
### Problem Description

reminder to do research and later implement automatic resize/compression when sending images.

### Proposed Solution

Maybe a option that ask if FD should resize/compress or send "as is".

### Alternatives Considered

Option in the configuration that globally enable/disable automatic resize/compression.

**Comment by DJ2LS** [comment]
@LA3QMA ready for testing

**Comment by DJ2LS** [comment]
@LA3QMA hows the image size? Should it be smaller in size? 
500x500px seems to be too much while 250x250px seems to be too small

**Comment by DJ2LS** [comment]
Okay, I increased this to 750px, less doesn't make that much sense as the images become too small. However, we have good compression results. But it should be clear, that sending images requires  a good channel and lot of data needs to move over the ether.

**Comment by dk5sm** [comment]
![heise](https://github.com/user-attachments/assets/17741485-1cfe-41cb-bdf5-9f00de37dabf)
![3percent_20240906_140344](https://github.com/user-attachments/assets/0f562e84-db84-46ae-bfa8-389f5b334be1)

I encountered some strange behaviour while using latest FD version and fiddling around with image compression:

1. The attached file 3percent_20240906_140344.jp is 121 x 68 px in size and results in:
![image](https://github.com/user-attachments/assets/5ce40974-0881-41e4-ba5a-ccffbe2c847b)

2. The attached file heise.png is 16 x 16 px (336 bytes!) and results in:
![image](https://github.com/user-attachments/assets/19d52f1d-a9c1-46dd-85d3-f615d7f66324)

The former can perhaps be explained with overhead, but the latter is weird....

**Comment by DJ2LS** [comment]
pushed a commit, please do a git pull and npm run build 
should be fixed now

**Comment by dk5sm** [comment]
Looks good now! The 226 bytes pic expands to 458 bytes, which is probably due to the normal overhead. The other one shrinks from 6915 to 2179 bytes.
