### ISSUE TITLE
[Feature Request]: "Message auto repeat" should resend messages when receiving ping/beacon

### ISSUE THREAD

**Issue by ND2W** [DJ2LS/FreeDATA#794]
### Problem Description

The "message auto repeat" feature, when enabled, resends any messages that were not transmitted successfully. It works as designed when the station that only received a part of a message transmits a beacon that is being received by the station that was sending the message.

However, FD should also resend an incomplete message 
- if a ping is received by either the sending or receiving station
- if a beacon is received by the receiving station (the station that only received part of the message)

### Proposed Solution

FD should check anytime it receives a ping or beacon from a station, 
- if there are any incomplete messages that should be resend to the pinging/beaconing station; and if this is the case, resume sending the message. 
- if there are any not completely received messages from the pinging/beaconing station. If so, FD could reply with a ping to that station in order ask to resume the transfer.

Since both station may detect at a similar time that they either have to resume the transfer, respectively request the other station to resume the transfer, the sending station station could always wait for the ping/beacon of the receiving station before it resumes the transfer.

### Alternatives Considered

N/A

**Comment by DJ2LS** [comment]
@ND2W implemented without testing with latest version. Please do a test as soon as possible. Thanks :-)
