### ISSUE TITLE
[Feature Request]: Blacklisting

### ISSUE THREAD

**Issue by OH2JRB** [DJ2LS/FreeDATA#797]
### Problem Description

Non-ham call signs (stations) are occasionally active on FreeDATA. A legitimate station may now inadvertently communicate with a pirate station.

### Proposed Solution

Introduce blacklisting, list editable in GUI.

### Alternatives Considered

Whitelisting allowed stations - too bureaucratic and requires constant maintenance.

### Additional Information

Log the call (attempt) but block sending data to and block ACK'ing any data sent by the call sign on the blacklist. 
Including blocking possible QRV reply to CQ.

**Comment by DJ2LS** [comment]
@OH2JRB first version published - please do a test if possible
