### ISSUE TITLE
[Bug]: RX/TX level adjust within 'tune' widget does not work

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#806]
### FreeDATA Version

0.16.4 (latest dev code as of 09/15)

### What operating system are you using?

Ubuntu

### Operating System Version

24.04.1

### Architecture

ARM Raspberry Pi

### Area of problem

GUI

### Describe the bug

Using the RX/TX level sliders within the 'Tune' widget has no effect. Only when using these controls within Settings -> Modem the Server restarts and the values are set.

### To Reproduce

1. click on 'Tune' widget
2. modify value for RX or TX
3. find that the server is not being restarted when ne value is set

### Expected behavior

Same behavior as within Settings/Modem.

**Comment by DJ2LS** [comment]
OnChange not imported in main modals. Should be an easy fix

**Comment by DJ2LS** [comment]
fixed, @dk5sm please test and confirm if its working. If so, please close the issue.

**Comment by dk5sm** [comment]
confirm - fixed.
