### ISSUE TITLE
[Bug]: IRS only responds on CQ

### ISSUE THREAD

**Issue by dk5sm** [DJ2LS/FreeDATA#811]
### FreeDATA Version

0.16.4-alpha

### What operating system are you using?

Ubuntu

### Operating System Version

24.04.1

### Architecture

ARM Raspberry Pi

### Area of problem

Server - Message System

### Describe the bug

Yesterday I noticed, that I seem to have a good path to a Norwegian station; it´s beacon showed an SNR of +3dB. So i tried bothe  ping and chat, but both without response from IRS. Only a CQ led to a response from this particular station.

### To Reproduce

not sure how to do this, as ping/connect formerly worked the same day.

### Expected behavior

ping and chat should result in an corresponding answer ;-)

**Comment by LA3QMA** [comment]
I can confirm this behavior. 19.09.2024 most of the stations i received was quite strong. After a CQ several stations reported and was updated in the list. Trying to send a message failed also ping. Can try to get the logs later todaty,

**Comment by DJ2LS** [comment]
Are we talking about repeating or sending a new message?

**Comment by LA3QMA** [comment]
I tried repeat and also a new message. Can try more later today to see if i can narrow it down.

**Comment by LA3QMA** [comment]
hmm only CQ is working
and regarding messages in queued
2024-09-20 19:36:36 [info     ] [DatabaseManagerMessages]: Set message LA3QMA-1_DJ2LS-1_2024-09-18T17:37:35.168180+00:00 to queued and incremented attempt
2024-09-20 19:36:36 [warning  ] [DatabaseManagerMessages]: An error occurred while setting messages to queued: object of type 'P2PMessage' has no len()

**Comment by DJ2LS** [comment]
Maybe this sticks together with the issue. If a message fails, it might have a wrong state. This results then into ignoring packages as we expect specific frames for specific states

**Comment by DJ2LS** [comment]
> hmm only CQ is working and regarding messages in queued 2024-09-20 19:36:36 [info ] [DatabaseManagerMessages]: Set message LA3QMA-1_DJ2LS-1_2024-09-18T17:37:35.168180+00:00 to queued and incremented attempt 2024-09-20 19:36:36 [warning ] [DatabaseManagerMessages]: An error occurred while setting messages to queued: object of type 'P2PMessage' has no len()

This one should be fixed now
