### ISSUE TITLE
[Bug]: Internal hamlib reports OK when transmitter is disconnected

### ISSUE THREAD

**Issue by danieldamon** [DJ2LS/FreeDATA#829]
### FreeDATA Version

0.16.8-alpha

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 24.04

### Architecture

x64

### Area of problem

Rig Control

### Describe the bug

Without the radio connected, FreeData reports everything is operational. I have rig set for TS480

### To Reproduce

1. disconnect radio
2. start FreeData
3. set rigctl to internal hamlib
4. See all green

### Expected behavior

Without a rig, indicator should be red

### Screenshots

none

**Comment by danieldamon** [comment]
This issue does not appear in Windows version 0.16.2-alpha, which was downloaded today.

**Comment by DJ2LS** [comment]
This issue sticks together with #827

**Comment by DJ2LS** [comment]
latest development code should work now. Can you confirm this, @danieldamon ? Otherwise we have to wait until we published a new release.

**Comment by danieldamon** [comment]
Sorry, continues the same incorrect way. 
I built by first deleting contents of FreeDATA, then executing
bash ./install-freedata-linux.sh develop

**Comment by DJ2LS** [comment]
Question is, if it's a Hamlib related topic. Means, if Hamlib is running fine, but just can't connect to the radio, it's hard to avoid the behaviour as we are checking the network connection. Not sure if we have a Hamlib related api command

**Comment by danieldamon** [comment]
Internal hamlib appears to be working correctly.  It changes frequency of my rig and causes it to transmit. At least on non-development.  I'll try there too

**Comment by danieldamon** [comment]
same deal with development
