### ISSUE TITLE
[Bug]: "VFO" slider in Rig setup not working

### ISSUE THREAD

**Issue by OH1KH** [DJ2LS/FreeDATA#833]
### FreeDATA Version

0.16.8-alpha (devel branch)

### What operating system are you using?

Other Linux

### Operating System Version

Fedora 40 (Linux hamtpad 6.10.11-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep 18 21:09:58 UTC 2024 x86_64 GNU/Linux)

### Architecture

x64

### Area of problem

Rig Control

### Describe the bug

Rigctld (internal hamlib):  Rig vfo parameter/ vfo slider has no effect.

### To Reproduce

Start freedata
Select rigctld(internal hamlib) and set rig settings right.
Set Rig vfo parameter/ vfo slider OFF
From command termnal give: ps ax | grep rig
See result:
[saku@hamtpad ~]$ ps ax | grep rig
   4599 pts/0    Sl+    0:00 /home/saku/freedata/FreeDATA-hamlib/bin/rigctld -m 3073 -r /dev/ttyUSB0 -s 19200 -P RIG -D NONE --set-conf data_bits=8 --set-conf stop_bits=1
Change  Rig vfo parameter/ vfo slider ON
From command termnal give: ps ax | grep rig
See result:
[saku@hamtpad ~]$ ps ax | grep rig
   4599 pts/0    Z+     0:00 [rigctld] <defunct>
   5269 pts/0    Sl+    0:00 /home/saku/freedata/FreeDATA-hamlib/bin/rigctld -m 3073 -r /dev/ttyUSB0 -s 19200 -P RIG -D NONE --set-conf data_bits=8 --set-conf stop_bits=1

Two notes:
Process number of rigctld has changed, so altering "vfo" slider has started a new rigctld.
- How ever the previous process has not been shut down properly and exists as zombie. (Fix this)
- Even when "vfo" slider was set to ON there is no "--vfo" parameter added to rigctld start parameters (Fix this)
- 

### Expected behavior

If "vfo" slider ON should add "--vfo" parameter to rigctld startup parameters and it should be seen in process listing too.
Previous rigcltd should be killed properly, not left in zombie state. (perhaps add wait between closing 1st and starting 2nd)

**Comment by DJ2LS** [comment]
thanks, I just pushed a commit which might fix the missing vfo parameter. The zombie process related part is a bit more tricky. Not sure if I will be able fixing it that fast.
